name: Linux Debug and Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'Stable*'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  BUILD_TYPE:   StableBuild

jobs:
  build:
    runs-on:  ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          dir:          ${{ runner.temp }}
          modules:      qtcharts
          setup-python: true

      - name: Install QGC source dependencies
        run:  sudo apt-get install -y libsdl2-dev

      - name: Install Gstreamer dev packages
        run:  sudo apt-get install -y libgstreamer-plugins-base1.0-dev libgstreamer1.0-0:amd64 libgstreamer1.0-dev

      - name: Install post-link dependencies
        run:  sudo apt-get install -y binutils patchelf

      - name: Create build directory
        run:  mkdir ${{ runner.temp }}/shadow_build_dir

      - name: Free up space
        run : |
            sudo df -h /
            sudo rm -rf ${ANDROID_SDK_ROOT}/ndk
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /usr/share/miniconda
            sudo rm -rf /usr/share/swift
            sudo df -h /

      - name: Build
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run:  |
              qmake -r ${SOURCE_DIR}/qgroundcontrol.pro CONFIG+=debug CONFIG+=${BUILD_TYPE}
              make -j2

      - name: Setup for unit tests
        working-directory: ${{ runner.temp }}/shadow_build_dir  
        run:  |
              mkdir -p ~/.config/QtProject/
              cp ${SOURCE_DIR}/test/qtlogging.ini ~/.config/QtProject/
              export QT_FATAL_WARNINGS=1

      - name: Run unit tests
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory:  ${{ runner.temp }}/shadow_build_dir  
          run:                ./staging/qgroundcontrol-start.sh --unittest
