name: Video App Linux

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'Stable*'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.6.*
  BUILD_TYPE:   ${{ fromJSON('["DailyBuild", "StableBuild"]')[ github.ref_type == 'tag' || contains(github.ref, 'Stable_' ) ] }}

jobs:
  build:
    runs-on:  ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          aqtversion:   ==3.1.*
          host:         linux
          target:       desktop
          dir:          ${{ runner.temp }}
          modules:      qtmultimedia
          setup-python: true

      - name: Install github environment dependencies for unit test running
        run:  sudo apt-get install libxcb-xinerama0 libxkbcommon-x11-0 libxcb-cursor0

      - name: Install QGC source dependencies
        run:  sudo apt-get install -y libsdl2-dev

      - name: Install Gstreamer dev packages
        run:  sudo apt-get install -y libgstreamer-plugins-base1.0-dev libgstreamer1.0-0:amd64 libgstreamer1.0-dev

      - name: Install post-link dependencies
        run:  sudo apt-get install -y binutils patchelf ninja-build
      - name: Create build directory
        run:  mkdir ${{ runner.temp }}/shadow_build_dir

      - name: Build
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run:  |
          cmake -S ${SOURCE_DIR}/VideoReceiverApp -B ${SOURCE_DIR}/VideoReceiverApp/shadow_build_dir/ -G Ninja
          cmake --build ${SOURCE_DIR}/VideoReceiverApp/shadow_build_dir/ --target all
